In [5]:
import pandas as pd # type: ignore
import numpy as np # type: ignore

In [19]:
# def create_random_matrix(n):
#     # Generate an n x n matrix filled with random 0s and 1s
#     matrix = np.random.randint(2, size=(n, n))
#     return matrix

# # Example usage
# n = 10
# puzzle_matrix = create_random_matrix(n)
# solArr = np.zeros(shape=(n, n))
# print(puzzle_matrix)
# print(solArr)

In [27]:
def isSafe(arr, x, y, n):
    if x<n and y<n and arr[x][y]==1:
        return True
    return False

def ratinMaze(arr, x, y, n, solArr):
    
    if x==n-1 and y==n-1:
        solArr[x][y] =1
        return True

    if isSafe(arr, x, y, n):
        solArr[x][y]=1
        if ratinMaze(arr, x+1, y, n, solArr):
            return True
        
        if ratinMaze(arr, x, y+1, n, solArr):
            return True
        solArr[x][y] = 0
        return False
    return False

# puzzel_matrix = [[1, 0, 1, 0, 1],
#                  [1, 1 ,1, 1, 1],
#                  [0, 1, 0, 1, 0],                               ######### Example Matrix #########
#                  [1, 0, 0, 1, 1],
#                  [1, 1, 1, 0, 1]]

n = 5                                                             # shape of input square matrix
def create_puzzel_matrix(n, ratio):
    total_elements = n * n
    num_ones = int(total_elements * ratio)
    num_zeros = total_elements - num_ones
    arr = np.array([1] * num_ones + [0] * num_zeros)
    np.random.shuffle(arr)
    matrix = arr.reshape((n, n))
    return matrix

solArr = np.zeros(shape=(n,n))

puzzel_matrix = create_puzzel_matrix(n, ratio=0.7)                # generatingg random puzzeles
print(puzzel_matrix)

ratinMaze(puzzel_matrix, 0, 0, n, solArr)
print(solArr)

[[1 1 0 0 1]
 [1 0 0 1 1]
 [1 1 1 1 1]
 [1 1 1 0 1]
 [0 0 1 0 1]]
[[1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]]
